"""Change phone column type

Revision ID: d99e1d6629e1
Revises: dfa00343b2b3
Create Date: 2024-09-12 06:37:52.193056

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd99e1d6629e1'
down_revision = 'dfa00343b2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
